### PR TITLE
feat: support client side redirects in Form component

### PR DESCRIPTION
**Pull request by itsMapleLeaf**
This PR makes it so the `<Form>` will perform a `router.push` if a redirect is returned from a server-side handler. Example from tests:

```ts
export const getServerSideProps = handle({
  get: () => {
    return json({});
  },
  patch: async () => {
    return redirect('/client-redirect/destination', { status: 303 });
  },
});

export default function ClientRedirect() {
  return (
    <Form method="patch">
      <input type="hidden" name="redirectStatus" value="303" />
      <button type="submit">Submit</button>
    </Form>
  );
}
```
```ts
// destination
export const getServerSideProps = handle({
  get: async () => {
    return json({
      message: 'The redirect has landed. 🚀',
    });
  },
});

export default function ClientRedirect({ message }: { message: string }) {
  return <p>{message}</p>;
}

```

Open to changes on how this should work, or if this just isn't a good idea 😅 Mostly just hacked it in to see if / how well it would work

### CODE REVIEW

**Comment by smeijer** [comment]
Sweet! I had the same idea about checking if the fetch got redirected. I do wonder though, should we not just reuse the `success` state for this? Maybe add a `redirect: ${url}` prop to that?

```
{ state: 'success'; data: Record<string, unknown>, redirect?: string }
```

The reasoning is, even tho the form submission is successful, the `onSuccess` handler is no longer called when the `post` handler redirects. I also don't have a way to act upon the data that the `fetch` returns. (fetch result includes data from `/destination`).

If we'd still treat it as a `success` state, and simply set `redirect?: string`, that will all be solved.

```js
setState({
  ...state,
  state: 'success',
  data: await response.json(),
  redirect: response.redirected ? response.url : undefined,
});
```

Regarding the `router.push` itself, I think that on redirect, `scroll` should be `true`. New pages are usually scrolled to top.

**Comment by smeijer** [comment]
Thanks! I've decided to apply the changes I described above, and merge this PR.

I've published this as https://github.com/smeijer/next-runtime/releases/tag/v1.3.0.

**Comment by smeijer** [comment]
@all-contributors please add @itsMapleLeaf for test

**Comment by smeijer** [comment]
I've also added you as a collaborator on the project. Please continue to make PRs as you feel the need. You can now make your branches directly on the repo rather than your fork if you want.

Thanks for your contributions! Much appreciated.

---

<p align="center">
  <a href="../blob/main/MAINTAINING.md">maintaining</a> | <a href="../blob/main/CONTRIBUTING.md">contributing</a> | <a href="https://help.github.com/articles/watching-repositories">watching</a> | <a href="https://contributor-covenant.org">covenant</a>
</p>

**Comment by itsMapleLeaf** [comment]
Sure thing, happy to help 😊

**Pull request merged**
