### PR TITLE
fix: type error for `ref` on `Form` component

### LINKED ISSUE #46: Type error in ref props of the Form component
First, thank you for such a nice library :tada:

There is a type error when I pass `ref` to the `<Form>` component (but, it works well, just a type error).

image

repro: https://stackblitz.com/edit/nextjs-9mtrvu?file=pages/index.tsx

### PR DESCRIPTION
**Pull request by KoichiKiyokawa**
fix #46

I fixed the cast in `Form` component. (I'm not sure if this is a good way.)
Feel free to edit my code.

### CODE REVIEW

**Comment by KoichiKiyokawa** [comment]
https://github.com/smeijer/next-runtime/actions/runs/1686452172
In my local environment, all tests succeed, but CI failed 🤔 
I force pushed to re-run CI, but it seems that first-time contributes cannot re-run CI by force pushing.

Could anyone re-run CI?

**Comment by smeijer** [comment]
They now pass :) Thanks! I'll look at your changes, and publish a new version during the weekend.

**Review by smeijer — APPROVED** [review]
Thanks! Looking great!

**Comment by smeijer** [comment]
@all-contributors please add @KoichiKiyokawa for code, test

**Pull request merged**
