### PR TITLE
chore: upgrade busboy to 1.6.0

### PR DESCRIPTION
**Pull request by PandiyanCool**
Fix: I have come across one dependency issue of package dicer

I have came across that latest busboy package is no longer using the dicer package.

So I have updated the dependencies and bit of code change to support the formats and error push methods.

(to make sure unit test is passing)

### CODE REVIEW

**Comment by PandiyanCool** [comment]
Hi @smeijer 

Can you review this? This is my first PR, and I'm not sure if I have completed everything as expected.

**Comment by smeijer** [comment]
hi @PandiyanCool , thanks for the contribution! Much appreciated.

I've reverted some of your changes, as removing testing logic to make it pass, is really a no-go, and many of the source/formatting changes were simply unneeded. 

I'm going ahead and merge & release this now. Thanks again!

**Comment by PandiyanCool** [comment]
Cheers!

**Comment by smeijer** [comment]
@all-contributors please add @PandiyanCool for code

**Pull request merged**
